### PR TITLE
Pacific power Missing Data

### PR DESCRIPTION
**Pull request by solderq35**
EDIT
Issue: https://github.com/OSU-Sustainability-Office/automated-jobs/issues/42

Example Logs (tested 11 PM April 9, 2024)
[04-09-2024-11pm.txt](https://github.com/OSU-Sustainability-Office/automated-jobs/files/14928584/04-09-2024-11pm.txt)
## Main Test Case Examples
- Meter `74364151`
  - Actual yesterday date: April 8
  - Current data in Energy Dashboard SQL database: Up to April 6
  - Latest data shown on Pacific Power site: Up to April 8
  - **Result**: April 7 and 8 data uploaded
- Meter `74364232`
  - Actual yesterday date: April 8
  - Current data in Energy Dashboard SQL database: Up to April 7
  - Latest data shown on Pacific Power site: Up to April 7
  - **Result**: Nothing uploaded, since April 7 data is already in Energy Dashboard SQL database

Will clean up comments and variable names later.

### CODE REVIEW

**Comment by solderq35** [comment]
This probably has some log statements that need to be cleaned up but functionally it's working.

## Example Use Case: 
[04-10-2024-09-52pm.txt](https://github.com/OSU-Sustainability-Office/automated-jobs/files/14972930/04-10-2024-09-52pm.txt)

## Code Logic
### Variables
-  Keep track of 2 pointers, `actual_days` and `row_day`
  - `actual_days` is X days ago (in terms of the actual date in general)
  - `row_days` is X days ago (in terms of what data is shown on Pacific Power site for a given meter)

### Control Flow
- For each meter:
  - If yearly time frame (monthly interval) data is detected, exit for loop early and don't enter the while loop below
  - While `actual_days` has not reached a week ago:
    - If "unavailable" or "delivered" text is found, exit while loop early and go to the next iteration of the while loop (`continue`)
      - Increment both `actual_days` and `row_days` (the PacificPower site data for that day is faulty)
    - If `actual_days` is the same as `row_days` initially, then valid data was detected for that day. Mark that data to be uploaded to SQL (If the data for that day and meter is not already marked to be uploaded / not already on SQL database)
      - Then keep incrementing both `actual_days` and `row_days` until a match with the latest date already uploaded to SQL database is detected (`matchingPPRecent` / `matchingPPRecentTime`). This is expected to be from 2 days ago, but it may be older in case there were missed uploads
     - If `actual_days` is less than `row_days` (e.g. for missed upload), then increment `actual_days`, but not `row_days`
       - This will allow `actual_days` and `row_days` to "sync" for cases where the data for a particular day is either not shown on PacificPower, or is bugged for that day ("unavailable" or "delivered" errors)
       - While incrementing `actual_days`, if valid data, then upload the data for that day (If the data for that day and meter is not already marked to be uploaded / not already on SQL database)

**Comment by solderq35** [comment]
New log file for reference: 
[04-23-2024-morning-10.txt](https://github.com/OSU-Sustainability-Office/automated-jobs/files/15081093/04-23-2024-morning-10.txt)

Command (tested on Windows command prompt / powershell): `node readPP.js --no-upload --save-output > logs/04-23-2024-morning-10.txt`

**Comment by solderq35** [comment]
New env file for this PR: https://drive.google.com/drive/u/3/folders/1geuKCp-aTIrde2WdJkE3f_L2TsF46_O3

**Review by s-egge — APPROVED** [review]
This looks good to me, I tested it by deleting data for some meters and it caught them added them back as expected.

**Comment by solderq35** [comment]
Should be set up to handle errors from ppRecent API endpoint not responding etc now.

**Comment by solderq35** [comment]
Follow-up task (future PR): https://github.com/OSU-Sustainability-Office/automated-jobs/issues/51

**Comment by solderq35** [comment]
## Update May 5 2024
- Polished up logs
- Moved some code out of `if (date !=== actual_date)` if / else statement to avoid redundancy
- In case of ppRecent API call failure, now just check the most recent data point on PacificPower site:
  - image

**Comment by solderq35** [comment]
Updated to check SQL database data (via energy dashboard API) from all 7 past days, and upload any missing data.

Simplified "wrong date" logic for log keeping.

Log status text if redundant upload (custom 400 error)

**Comment by solderq35** [comment]
Will fix merge errors on readPP.js later this week (put this comment to remind myself).

**Comment by solderq35** [comment]
Merging this was more complex than anticipated.

## Summary of Changes:
- Ensured that `compareMeterAgainstExclusionList` function is only called after getting through ppRecent logic, and that everything works as expected:
  - ppRecent and ppExclude API calls both succeed > past 7 days' (non-duplicate) data uploaded, exclusion logic applied
  - ppRecent API call fails and ppExclude API call succeeds > most recent day's data uploaded, exclusion logic applied
  - ppRecent API call succeeds and ppExclude API call fails > past 7 days' (non-duplicate) data uploaded, no exclusion logic applied
  - ppRecent and ppExclude API calls both fail > most recent day's data uploaded, no exclusion logic applied
    - As discussed earlier, there is a final server-side check for redundant uploads (return status 400 if meter ID and time_seconds values both match)
- Only push unique meter ID's into the exclusion / inclusion lists (to avoid duplicate entries from 7 days' worth of data)

## Other Testing Notes
- Test against this energy-dashboard branch (and / or merge this PR if it looks ok): https://github.com/OSU-Sustainability-Office/energy-dashboard/pull/327
- For testing the control flow, change the status code checks for ppRecent and ppExclude API calls, e.g. change `if (res.status < 200 || res.status >= 300) {` to `if (res.status == 200) {`

**Comment by solderq35** [comment]
Added status text log for pprecent api endpoint as well (to match ppexclude endpoint status log)

image

**Pull request merged**
